return {
    ["host_conf"] =
    {
        {id = 1, localip = "172.20.68.146", ip = "172.20.68.146", domain = "47.96.6.230", desc = "主播服-游戏", netid = 1},
        --{id = 2, localip = "172.31.124.206", ip = "47.111.165.152", domain = "47.111.165.152", desc = "二区太湖仙岛", netid = 1}
    },
    ["process_conf"] =
    {
        { id = 8, hostid = 1, desc = "集群服务", group = {2, 3}, name = "Cluster_tlbb_8"},
        { id = 9, hostid = 1, desc = "数据服务", group = {2, 3, 5, 7}, name = "DataCenter_tlbb_8"},
        { id = 2, hostid = 1, desc = "游戏服务-2", group = {2}, name = "Game_tlbb_2"},
        { id = 3, hostid = 1, desc = "游戏服务-3", group = {3}, name = "Game_tlbb_3"},
        { id = 4, hostid = 1, desc = "天外服务-4", group = {2, 3, 5}, name = "Span_tlbb_4"},
        { id = 5, hostid = 2, desc = "游戏服务-5", group = {5}, name = "Game_tlbb_5"},
        { id = 6, hostid = 1, desc = "工具服务-6", group = {2, 3, 5}, name = "Tool_tlbb_4"},
        { id = 7, hostid = 2, desc = "游戏服务-7", group = {7}, name = "Game_tlbb_7"},
        { id = 10, hostid = 1, desc = "天外服务-10", group = {7}, name = "Span_tlbb_10"},
    },
    ["server_conf"] =
    {
        {id = 8001, name = "clusterd", alias = "clusterd", processid = 8, desc = "集群服务-clusted", port = 8888, ctor_args = {}, init_args = {true}, private = true},
        {id = 8002, name = "cfgdb", alias = ".CfgDB", processid = 8, desc = "配置服务-clusted", port = 0, ctor_args = {}, init_args = {true}, private = false},

        {id = 2001, name = "clusterd", alias = "clusterd", processid = 2, desc = "游戏-clusted", port = 2528, ctor_args = {}, init_args = {true}, private = true},
        {id = 2002, name = "debug_console", alias = "debug_console", processid = 2, desc = "游戏-debug_console", port = 6002, ctor_args = {}, init_args = {}, private = true},
        {id = 2003, name = "dbproxy", alias = ".db", processid = 2, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_10" }, private = true},
        {id = 2004, name = "dbproxy", alias = ".char_db", processid = 2, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 2005, name = "dbproxy", alias = ".logdb", processid = 2, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 2006, name = "gen_serial", alias = ".gen_serial", processid = 2, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 10 }, private = true},
        {id = 2007, name = "agent_poll", alias = ".agent_poll", processid = 2, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 2008, name = "world", alias = ".world", processid = 2, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 10} }, private = false},
        {id = 2009, name = "guildmanager", alias = ".Guildmanager", processid = 2, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2010, name = "scenemanager", alias = ".SceneManager", processid = 2, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 10} }, private = false},
        {id = 2011, name = "playermanager", alias = ".Playermanager", processid = 2, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 2, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 10}}, private = false},
        {id = 2013, name = "activity", alias = ".Activitymanager", processid = 2, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2014, name = "ybexchange", alias = ".Ybexchange", processid = 2, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 2, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 10}}, private = false},
        {id = 2016, name = "gamed", alias = ".gamed", processid = 2, desc = "游戏服", port = 3731, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 10}}, private = false},
        {id = 2017, name = "logind", alias = ".logind", processid = 2, desc = "登录服", port = 3733, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 10}}, private = false},

        {id = 3001, name = "clusterd", alias = "clusterd", processid = 3, desc = "游戏-clusted", port = 2529, ctor_args = {}, init_args = {true}, private = true},
        {id = 3002, name = "debug_console", alias = "debug_console", processid = 3, desc = "游戏-debug_console", port = 6003, ctor_args = {}, init_args = {}, private = true},
        {id = 3003, name = "dbproxy", alias = ".db", processid = 3, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_11" }, private = true},
        {id = 3004, name = "dbproxy", alias = ".char_db", processid = 3, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 3005, name = "dbproxy", alias = ".logdb", processid = 3, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 3006, name = "gen_serial", alias = ".gen_serial", processid = 3, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 11 }, private = true},
        {id = 2007, name = "agent_poll", alias = ".agent_poll", processid = 3, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 3008, name = "world", alias = ".world", processid = 3, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 11} }, private = false},
        {id = 3009, name = "guildmanager", alias = ".Guildmanager", processid = 3, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3010, name = "scenemanager", alias = ".SceneManager", processid = 3, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 11} }, private = false},
        {id = 3011, name = "playermanager", alias = ".Playermanager", processid = 3, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 3, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 11}}, private = false},
        {id = 3013, name = "activity", alias = ".Activitymanager", processid = 3, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3014, name = "ybexchange", alias = ".Ybexchange", processid = 3, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 3, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 11}}, private = false},
        {id = 3016, name = "gamed", alias = ".gamed", processid = 3, desc = "游戏服", port = 3732, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 11}}, private = false},
        {id = 3017, name = "logind", alias = ".logind", processid = 3, desc = "登录服", port = 3734, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 11}}, private = false},

        {id = 4001, name = "clusterd", alias = "clusterd", processid = 4, desc = "游戏-clusted", port = 2530, ctor_args = {}, init_args = {true}, private = true},
        {id = 4002, name = "debug_console", alias = "debug_console", processid = 4, desc = "游戏-debug_console", port = 6004, ctor_args = {}, init_args = {}, private = true},
        {id = 4003, name = "dbproxy", alias = ".db", processid = 4, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_10" }, private = true},
        {id = 4004, name = "dbproxy", alias = ".logdb", processid = 4, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 4005, name = "gen_serial", alias = ".gen_serial", processid = 4, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 8 }, private = true},
        {id = 4006, name = "spanscene", alias = ".SCENE_1297", processid = 4, desc = "天外-长春谷·不老殿", port = 0, ctor_args = {}, init_args = {{ id = 1297, world_id = 8 }}, private = false},
        {id = 4007, name = "spanscene", alias = ".SCENE_1298", processid = 4, desc = "天外-藏经阁", port = 0, ctor_args = {}, init_args = {{ id = 1298, world_id = 8 }}, private = false},
        {id = 4008, name = "spanscene", alias = ".SCENE_1299", processid = 4, desc = "天外-地宫4", port = 0, ctor_args = {}, init_args = {{ id = 1299, world_id = 8 }}, private = false},

        {id = 5001, name = "clusterd", alias = "clusterd", processid = 5, desc = "游戏-clusted", port = 2535, ctor_args = {}, init_args = {true}, private = true},
        {id = 5002, name = "debug_console", alias = "debug_console", processid = 5, desc = "游戏-debug_console", port = 6005, ctor_args = {}, init_args = {}, private = true},
        {id = 5003, name = "dbproxy", alias = ".db", processid = 5, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_12" }, private = true},
        {id = 5004, name = "dbproxy", alias = ".char_db", processid = 5, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 5005, name = "dbproxy", alias = ".logdb", processid = 5, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 5006, name = "gen_serial", alias = ".gen_serial", processid = 5, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 12 }, private = true},
        {id = 5007, name = "agent_poll", alias = ".agent_poll", processid = 5, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 5008, name = "world", alias = ".world", processid = 5, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 12} }, private = false},
        {id = 5009, name = "guildmanager", alias = ".Guildmanager", processid = 5, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5010, name = "scenemanager", alias = ".SceneManager", processid = 5, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 12} }, private = false},
        {id = 5011, name = "playermanager", alias = ".Playermanager", processid = 5, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 5, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 12}}, private = false},
        {id = 5013, name = "activity", alias = ".Activitymanager", processid = 5, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5014, name = "ybexchange", alias = ".Ybexchange", processid = 5, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 5, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 12}}, private = false},
        {id = 5016, name = "gamed", alias = ".gamed", processid = 5, desc = "游戏服", port = 3735, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 12}}, private = false},
        {id = 5017, name = "logind", alias = ".logind", processid = 5, desc = "登录服", port = 3736, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 12}}, private = false},

        {id = 6001, name = "clusterd", alias = "clusterd", processid = 6, desc = "工具服务-clusted", port = 2532, ctor_args = {}, init_args = {true}, private = true},
        {id = 6002, name = "debug_console", alias = "debug_console", processid = 6, desc = "工具服务-debug_console", port = 6006, ctor_args = {}, init_args = {}, private = true},
        {id = 6003, name = "dbproxy", alias = ".char_db", processid = 6, desc = "角色数据源", port = 0, ctor_args = {}, init_args = {  "gamedb", "tlbb"  }, private = true},
        {id = 6004, name = "register", alias = ".register", processid = 6, desc = "注册服务", port = 13010, ctor_args = {}, init_args = {true}, private = false},
        {id = 6005, name = "pay", alias = ".pay", processid = 6, desc = "订单服务", port = 13011, ctor_args = {}, init_args = {}, private = false},
        {id = 6006, name = "payend", alias = ".payend", processid = 6, desc = "支付回调服务", port = 13012, ctor_args = {}, init_args = {}, private = false},
        {id = 6007, name = "mysqldb", alias = ".mysqldb", processid = 6, desc = "mysql数据库服务", port = 0, ctor_args = {}, init_args = {true}, private = false},

        {id = 7001, name = "clusterd", alias = "clusterd", processid = 7, desc = "游戏-clusted", port = 2537, ctor_args = {}, init_args = {true}, private = true},
        {id = 7002, name = "debug_console", alias = "debug_console", processid = 7, desc = "游戏-debug_console", port = 6007, ctor_args = {}, init_args = {}, private = true},
        {id = 7003, name = "dbproxy", alias = ".db", processid = 7, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_13" }, private = true},
        {id = 7004, name = "dbproxy", alias = ".char_db", processid = 7, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 7005, name = "dbproxy", alias = ".logdb", processid = 7, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 7006, name = "gen_serial", alias = ".gen_serial", processid = 7, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 13 }, private = true},
        {id = 7007, name = "agent_poll", alias = ".agent_poll", processid = 7, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 7008, name = "world", alias = ".world", processid = 7, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 13} }, private = false},
        {id = 7009, name = "guildmanager", alias = ".Guildmanager", processid = 7, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 7010, name = "scenemanager", alias = ".SceneManager", processid = 7, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 13} }, private = false},
        {id = 7011, name = "playermanager", alias = ".Playermanager", processid = 7, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 7012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 7, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 13}}, private = false},
        {id = 7013, name = "activity", alias = ".Activitymanager", processid = 7, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 7014, name = "ybexchange", alias = ".Ybexchange", processid = 7, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 7015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 7, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 13}}, private = false},
        {id = 7016, name = "gamed", alias = ".gamed", processid = 7, desc = "游戏服", port = 3737, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 13}}, private = false},
        {id = 7017, name = "logind", alias = ".logind", processid = 7, desc = "登录服", port = 3738, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 13}}, private = false},

        {id = 9001, name = "clusterd", alias = "clusterd", processid = 9, desc = "数据中心-clusted", port = 2531, ctor_args = {}, init_args = {true}, private = true},
        {id = 9002, name = "debug_console", alias = "debug_console", processid = 9, desc = "数据中心-debug_console", port = 6009, ctor_args = {}, init_args = {}, private = true},
        {id = 9003, name = "clusterdatacenterd", alias = ".CDATACENTERD", processid = 9, desc = "数据中心服务", port = 0, ctor_args = {}, init_args = {}, private = false},

        {id = 10001, name = "clusterd", alias = "clusterd", processid = 10, desc = "游戏-clusted", port = 2540, ctor_args = {}, init_args = {true}, private = true},
        {id = 10002, name = "debug_console", alias = "debug_console", processid = 10, desc = "游戏-debug_console", port = 6010, ctor_args = {}, init_args = {}, private = true},
        {id = 10003, name = "dbproxy", alias = ".db", processid = 10, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_7" }, private = true},
        {id = 10004, name = "dbproxy", alias = ".logdb", processid = 10, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 10005, name = "gen_serial", alias = ".gen_serial", processid = 10, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 7 }, private = true},
        {id = 10006, name = "spanscene", alias = ".SCENE_1297", processid = 10, desc = "天外-长春谷·不老殿", port = 0, ctor_args = {}, init_args = {{ id = 1297, world_id = 7 }}, private = false},
        {id = 10007, name = "spanscene", alias = ".SCENE_1298", processid = 10, desc = "天外-藏经阁", port = 0, ctor_args = {}, init_args = {{ id = 1298, world_id = 7 }}, private = false},
        {id = 10008, name = "spanscene", alias = ".SCENE_1299", processid = 10, desc = "天外-地宫4", port = 0, ctor_args = {}, init_args = {{ id = 1299, world_id = 7 }}, private = false},
    }
}