root = "./"
env_conf_root = root .. "confs/" .. env .. "/"
framework_root = root .. "framework/"

luaservice = root .. "service/?.lua;"
.. framework_root .. "service/?.lua;"
.. root .. "?.lua;"
.. root .. "services/?.lua;"
.. root .. "services/login/?.lua;"
.. root .. "services/game/?.lua;"
.. root .. "services/scene/?.lua;"
.. root .. "services/world/?.lua;"
.. root .. "services/activity/?.lua;"
.. root .. "services/robot/?.lua;"
.. root .. "services/guild/?.lua;"
.. root .. "services/ybexchange/?.lua;"
.. root .. "services/msgagent/?.lua;"
.. root .. "services/web/?.lua;"
.. root .. "cluster/service/?.lua;"
.. framework_root .. "service/?.lua;"

lualoader = framework_root .. "lualib/loader.lua"

lua_path = framework_root .. "lualib/?.lua;"
.. framework_root .. "lualib/?/init.lua;"
.. script_root .. "/?.lua;"
.. root .. "services/?.lua;"
.. root .. "cluster/?.lua;"
.. root .. "lualib/?.lua;"
.. root .. "lualib/web/?.lua;"
.. root .. "msgagent_module/?.lua;"
.. env_conf_root .. "?.lua;"

lua_cpath = framework_root .. "luaclib/?.so;"
.. root .. "luaclib/?.so;"

snax = root .. "services/?.lua;"
.. root .. "?.lua;"

cpath = root .. "framework/cservice/?.so;"
.. root .. "cservice/?.so;"

preload = "./lualib/preloader.lua"