return {
    ["host_conf"] =
    {
        {id = 1, localip = "127.0.0.1", ip = "127.0.0.1", domain = "127.0.0.1", desc = "本地环境", netid = 1}
    },
    ["process_conf"] =
    {
        { id = 8, hostid = 1, desc = "集群服务", group = {2, 3}, name = "Cluster_tlbb_8"},
        { id = 9, hostid = 1, desc = "数据服务", group = {2, 3}, name = "DataCenter_tlbb_8"},
        { id = 2, hostid = 1, desc = "游戏服务-2", group = {2}, name = "Game_tlbb_2"},
        { id = 3, hostid = 1, desc = "游戏服务-3", group = {3}, name = "Game_tlbb_3"},
        { id = 4, hostid = 1, desc = "天外服务-4", group = {2, 3, 5}, name = "Span_tlbb_4"},
        { id = 5, hostid = 1, desc = "游戏服务-5", group = {5}, name = "Game_tlbb_5"},
        { id = 6, hostid = 1, desc = "工具服务-6", group = {2, 3, 5}, name = "Tool_tlbb_4"},
    },
    ["server_conf"] =
    {
        {id = 8001, name = "clusterd", alias = "clusterd", processid = 8, desc = "集群服务-clusted", port = 8888, ctor_args = {}, init_args = {true}, private = true},
        {id = 8002, name = "cfgdb", alias = ".CfgDB", processid = 8, desc = "配置服务-clusted", port = 0, ctor_args = {}, init_args = {true}, private = false},

        {id = 2001, name = "clusterd", alias = "clusterd", processid = 2, desc = "游戏-clusted", port = 2528, ctor_args = {}, init_args = {true}, private = true},
        {id = 2002, name = "debug_console", alias = "debug_console", processid = 2, desc = "游戏-debug_console", port = 6002, ctor_args = {}, init_args = {}, private = true},
        {id = 2003, name = "dbproxy", alias = ".db", processid = 2, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_10" }, private = true},
        {id = 2004, name = "dbproxy", alias = ".char_db", processid = 2, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 2005, name = "dbproxy", alias = ".logdb", processid = 2, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 2006, name = "gen_serial", alias = ".gen_serial", processid = 2, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 10 }, private = true},
        {id = 2007, name = "agent_poll", alias = ".agent_poll", processid = 2, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 2008, name = "world", alias = ".world", processid = 2, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 10} }, private = false},
        {id = 2009, name = "guildmanager", alias = ".Guildmanager", processid = 2, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2010, name = "scenemanager", alias = ".SceneManager", processid = 2, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 10} }, private = false},
        {id = 2011, name = "playermanager", alias = ".Playermanager", processid = 2, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 2, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 10}}, private = false},
        {id = 2013, name = "activity", alias = ".Activitymanager", processid = 2, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2014, name = "ybexchange", alias = ".Ybexchange", processid = 2, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 2, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 10}}, private = false},
        {id = 2016, name = "clusteragentproxy", alias = ".clusteragentproxy", processid = 2, desc = "集群玩家agent代理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2017, name = "xylogger", alias = ".xylogger", processid = 2, desc = "统计协议", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 2018, name = "gamed", alias = ".gamed", processid = 2, desc = "游戏服", port = 3731, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 10}}, private = false},
        {id = 2019, name = "logind", alias = ".logind", processid = 2, desc = "登录服", port = 3733, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 10, mac_max_client = 2}}, private = false},

        {id = 3001, name = "clusterd", alias = "clusterd", processid = 3, desc = "游戏-clusted", port = 2529, ctor_args = {}, init_args = {true}, private = true},
        {id = 3002, name = "debug_console", alias = "debug_console", processid = 3, desc = "游戏-debug_console", port = 6003, ctor_args = {}, init_args = {}, private = true},
        {id = 3003, name = "dbproxy", alias = ".db", processid = 3, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_11" }, private = true},
        {id = 3004, name = "dbproxy", alias = ".char_db", processid = 3, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 3005, name = "dbproxy", alias = ".logdb", processid = 3, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 3006, name = "gen_serial", alias = ".gen_serial", processid = 3, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 11 }, private = true},
        {id = 2007, name = "agent_poll", alias = ".agent_poll", processid = 3, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 3008, name = "world", alias = ".world", processid = 3, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 11} }, private = false},
        {id = 3009, name = "guildmanager", alias = ".Guildmanager", processid = 3, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3010, name = "scenemanager", alias = ".SceneManager", processid = 3, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 11} }, private = false},
        {id = 3011, name = "playermanager", alias = ".Playermanager", processid = 3, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 3, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 11}}, private = false},
        {id = 3013, name = "activity", alias = ".Activitymanager", processid = 3, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3014, name = "ybexchange", alias = ".Ybexchange", processid = 3, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 3, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 11}}, private = false},
        {id = 3016, name = "clusteragentproxy", alias = ".clusteragentproxy", processid = 3, desc = "集群玩家agent代理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 3017, name = "gamed", alias = ".gamed", processid = 3, desc = "游戏服", port = 3732, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 11}}, private = false},
        {id = 3018, name = "logind", alias = ".logind", processid = 3, desc = "登录服", port = 3734, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 11, mac_max_client = 2}}, private = false},

        {id = 4001, name = "clusterd", alias = "clusterd", processid = 4, desc = "游戏-clusted", port = 2530, ctor_args = {}, init_args = {true}, private = true},
        {id = 4002, name = "debug_console", alias = "debug_console", processid = 4, desc = "游戏-debug_console", port = 6004, ctor_args = {}, init_args = {}, private = true},
        {id = 4003, name = "dbproxy", alias = ".db", processid = 4, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_10" }, private = true},
        {id = 4004, name = "dbproxy", alias = ".logdb", processid = 4, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 4005, name = "gen_serial", alias = ".gen_serial", processid = 4, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 8 }, private = true},
        {id = 4006, name = "spanscene", alias = ".SCENE_1297", processid = 4, desc = "天外-长春谷·不老殿", port = 0, ctor_args = {}, init_args = {{ id = 1297, world_id = 8 }}, private = false},
        {id = 4007, name = "spanscene", alias = ".SCENE_1298", processid = 4, desc = "天外-藏经阁", port = 0, ctor_args = {}, init_args = {{ id = 1298, world_id = 8 }}, private = false},
        {id = 4008, name = "spanscene", alias = ".SCENE_1299", processid = 4, desc = "天外-地宫4", port = 0, ctor_args = {}, init_args = {{ id = 1299, world_id = 8 }}, private = false},
        {id = 4009, name = "spanscene", alias = ".SCENE_1300", processid = 4, desc = "天外-乌衣巷", port = 0, ctor_args = {}, init_args = {{ id = 1300, world_id = 8 }}, private = false},
        {id = 4010, name = "spanscene", alias = ".SCENE_1301", processid = 4, desc = "天外-江湖茶馆", port = 0, ctor_args = {}, init_args = {{ id = 1301, world_id = 8 }}, private = false},
        {id = 4011, name = "spancopyscenemanager", alias = ".Copyscenemanager", processid = 4, desc = "天外-副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 8}}, private = false},

        {id = 5001, name = "clusterd", alias = "clusterd", processid = 5, desc = "游戏-clusted", port = 2535, ctor_args = {}, init_args = {true}, private = true},
        {id = 5002, name = "debug_console", alias = "debug_console", processid = 5, desc = "游戏-debug_console", port = 6005, ctor_args = {}, init_args = {}, private = true},
        {id = 5003, name = "dbproxy", alias = ".db", processid = 5, desc = "世界数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "world_12" }, private = true},
        {id = 5004, name = "dbproxy", alias = ".char_db", processid = 5, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "gamedb", "tlbb" }, private = true},
        {id = 5005, name = "dbproxy", alias = ".logdb", processid = 5, desc = "角色数据源", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 5006, name = "gen_serial", alias = ".gen_serial", processid = 5, desc = "物品GUID生成", port = 0, ctor_args = {}, init_args = { 12 }, private = true},
        {id = 5007, name = "agent_poll", alias = ".agent_poll", processid = 5, desc = "agent池", port = 0, ctor_args = {}, init_args = { true }, private = true},
        {id = 5008, name = "world", alias = ".world", processid = 5, desc = "游戏世界", port = 0, ctor_args = {}, init_args = { {server_id = 12} }, private = false},
        {id = 5009, name = "guildmanager", alias = ".Guildmanager", processid = 5, desc = "帮会管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5010, name = "scenemanager", alias = ".SceneManager", processid = 5, desc = "场景管理服", port = 0, ctor_args = {}, init_args = { { world_id = 12} }, private = false},
        {id = 5011, name = "playermanager", alias = ".Playermanager", processid = 5, desc = "角色管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5012, name = "copyscenemanager", alias = ".Copyscenemanager", processid = 5, desc = "副本场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 12}}, private = false},
        {id = 5013, name = "activity", alias = ".Activitymanager", processid = 5, desc = "活动管理", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5014, name = "ybexchange", alias = ".Ybexchange", processid = 5, desc = "元宝交易所", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 5015, name = "dynamicscenemanager", alias = ".Dynamicscenemanager", processid = 5, desc = "动态场景管理", port = 0, ctor_args = {}, init_args = {{ world_id = 12}}, private = false},
        {id = 5016, name = "gamed", alias = ".gamed", processid = 5, desc = "游戏服", port = 3735, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 4096, nodelay = true, server_id = 12}}, private = false},
        {id = 5017, name = "logind", alias = ".logind", processid = 5, desc = "登录服", port = 3736, ctor_args = {}, init_args = {{address = "0.0.0.0", maxclient = 1024, nodelay = true, server_id = 12, mac_max_client = 2}}, private = false},

        {id = 6001, name = "clusterd", alias = "clusterd", processid = 6, desc = "工具服务-clusted", port = 2532, ctor_args = {}, init_args = {true}, private = true},
        {id = 6002, name = "debug_console", alias = "debug_console", processid = 6, desc = "工具服务-debug_console", port = 6006, ctor_args = {}, init_args = {}, private = true},
        {id = 6003, name = "dbproxy", alias = ".char_db", processid = 6, desc = "角色数据源", port = 0, ctor_args = {}, init_args = {  "gamedb", "tlbb"  }, private = true},
        {id = 6004, name = "dbproxy", alias = ".admin_db", processid = 6, desc = "web管理", port = 0, ctor_args = {}, init_args = {  "gamedb", "web_admin"  }, private = true},
        {id = 6005, name = "register", alias = ".register", processid = 6, desc = "注册服务", port = 13010, ctor_args = {}, init_args = {true}, private = false},
        {id = 6006, name = "pay", alias = ".pay", processid = 6, desc = "订单服务", port = 13011, ctor_args = {}, init_args = {}, private = false},
        {id = 6007, name = "payend", alias = ".payend", processid = 6, desc = "支付回调服务", port = 13012, ctor_args = {}, init_args = {}, private = false},
        {id = 6008, name = "mysqldb", alias = ".mysqldb", processid = 6, desc = "mysql数据库服务", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 6009, name = "web", alias = ".web", processid = 6, desc = "web", port = 0, ctor_args = {}, init_args = {{ protocol = 'http',port = 9000}}, private = false},
        {id = 6010, name = "ranking", alias = ".ranking", processid = 6, desc = "排行榜服务", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 6011, name = "monitor", alias = ".monitor", processid = 6, desc = "游戏监控", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 6012, name = "dbproxy", alias = ".logdb", processid = 6, desc = "日志库", port = 0, ctor_args = {}, init_args = { "logdb", "tlbb_log" }, private = true},
        {id = 6013, name = "textfilter_mgr", alias = ".textfilter", processid = 6, desc = "敏感词", port = 0, ctor_args = {}, init_args = {}, private = false},
        {id = 6014, name = "hs_admin", alias = ".hs_admin", processid = 6, desc = "admin服务", port = 13013, ctor_args = {}, init_args = {true}, private = false},
        {id = 6015, name = "mqttor", alias = ".mqttor", processid = 6, desc = "mqtt服务", port = 0, ctor_args = {}, init_args = {true}, private = false},
        {id = 6016, name = "gm_tool", alias = ".gm_tool", processid = 6, desc = "gm tool", port = 0, ctor_args = {}, init_args = {true}, private = false},

        {id = 9001, name = "clusterd", alias = "clusterd", processid = 9, desc = "数据中心-clusted", port = 2531, ctor_args = {}, init_args = {true}, private = true},
        {id = 9002, name = "debug_console", alias = "debug_console", processid = 9, desc = "数据中心-debug_console", port = 6009, ctor_args = {}, init_args = {}, private = true},
        {id = 9003, name = "clusterdatacenterd", alias = ".CDATACENTERD", processid = 9, desc = "数据中心服务", port = 0, ctor_args = {}, init_args = {}, private = false},
    }
}